
* mimo-ofdm 
** OFDM 
正交频分复用(orthogonal frequency-division multiplexing)。
ofdm使用大量紧邻的正交子载波（orthogonal-sub-carrier），每个子载波采用传统的调整方案进行低符号率调制。
*** 正交子载波
sin(t), sin(2t)...sin(xt)在(0,2*pi)区间上的积分为0。
a*sin(t) + b*sin(2t) 在接收端进行积分检测，既可以还原得到a和b。
易得sin(t) cos(t) 在(0,2*pi)区间上的积分为0。
得到 
- f(t)=∑ak·sin(2π·Δf·kt) + ∑bk·cos(2π·Δf·kt)
其中，2π是常量；Δf是事先选好的载频间隔，也是常量。
1t,2t,3t,...,kt保证了正弦波序列的正交性。
将t离散化，即为离散傅里叶变换的表达式。
*** 频域上的OFDM
频域上两路信号的距离可完全等同于奈奎斯特带宽。
码元速率为1/T(即每个码元的传输时长为T)，进行无码间串扰传输时，所需的最小带宽称为奈奎斯特带宽。
OFDM正交子载波，载频间距为奈奎斯特带宽，可以保证最大的频带利用率。
**** LTE的频率利用率分析
子载波的间隔Δf=15kHz，一个OFDM symbol的发送时间是66.7us。
在10MHz信道上，1ms的子帧共传输14个OFDM symbol【不是15个，留空给CP了】，每一个OFDM symbol携带600个复数信息，因此：
1) 从整个系统来看，波特率为600*14*2/1ms = 16.8MBaud，占据带宽10MHz，因此带宽利用率为16.8MBaud/10MHz = 1.68Baud/Hz，接近2Baud/Hz的理想情况。  
  【注：一是CP占用了每个OFDM Symbol约1/15的资源，二是10MHz的频带并不是满打满算的用于传输数据，其边界频带需要留空以减少与邻近信道的干扰】
2) 单从OFDM一个symbol来看，波特率为600*2/66.7us = 18MBaud，占据带宽600*15kHz=9MHz【不考虑边界子载波带外问题】，
   因此其带宽利用率为18MBaud/9MHz=2Baud/Hz，符合上面的讨论。
3) 附：5M带宽的WCDMA的chip rate = 3.84M/s，即码率为3.84M*2 = 7.68MBaud。
   带宽5M，所以带宽利用率为7.68MBaud/5MHz = 1.536Baud/Hz，略逊于LTE的1.68Baud/Hz
   注：WCDMA的脉冲成型采用滚降系数为0.22的升余弦滤波器，奈奎斯特带宽为3.84M】
*** 用IFFT实现OFDM
- fn = 1/N·∑Fk·e(j·2π·k·n/N) 
  【公式3-1，n为时域离散后的序号，N为总的IFFT个数，n∈[1,N]】
- 在一个OFDM symbol的时长T内，用N个子载波各自发送一个信号F(k)（k∈[1,N]），等效于直接在时域上连续发送fn（n∈[1,N]）N个信号，每个信号发送T/N的时长。
- 在IFFT实现OFDM中，发送端添加了IFFT模块、接收端添加了FFT模块。
  IFFT模块的功能相当于说：别麻烦发送N个子载波信号了，我直接算出你们在空中会叠加成啥样子吧；
  FFT模块的功能相当于说：别用老式的积分方法来去除其余的正交子载波了，我帮你一次把N个携带信号全算出来吧。
  就是这样，IFFT实现OFDM的系统用"数学的方法"，在发送端计算信号的叠加波形，在接收端去除正交子载波，从而大大简化了系统的复杂度。
*** OFDM 系统架构
**** TX
- 编码扰码 :: 校验编码，扰码，分集。提高鲁棒性。
- 星座映射 :: 二进制数据转换成实数域或者复数域。
          通信系统的星座映射与调制模块的本质是为二进制比特选取匹配物理信道的传输波形。
- IFFT     :: 频域信号转换到时域
- 并串转换 :: 并行数据转换成串行数据
- CP加窗   :: cp 循环前缀（抵抗多径效应），加窗（减少带外能量）
**** RX
- tx 逆过程。

** MIMO
利用发射端的多个天线各自独立发送信号，同时在接收端用多个天线接收并恢复原信息，就可以实现以更小的代价达到更高的用户速率。
主要是两个关键技术，空间分集和空间复用。
*** 空间分集
多根天线讲具有相同信息的信号，通过不同的路径发送出去，同时在接收机端得到同一个数据符号的多个独立衰落的信号，从而提高接受的可靠性。
- 空时分组码   :: 编码后数据正交，利用正交性可恢复原数据信号。编码成多组数据。（SFBC，空频编码）
- 波束成形技术 :: 用不同的发射天线来发射相同的数据，形成指向某些用户的赋形波束，从而提高天线的增益。
*** 空间复用
将要传送的数据分成几个数据流，然后在不同的天线上传输，从而提高系统的传输速率。
V-Blast（垂直分层空时码）。
*** MIMO OFDM系统架构
- 发射端
  1. 先对代发信息进行空时编码或者空频编码，然后根据多路天线，进行多路映射。
  2. 将各路数据按照OFDM架构将数据进行分集，映射，然后经过IFFT，上变频，然后由不同的天线输出。
- 接收端
  1. 需要有能量检测，检测发送信号的到达，并通过帧头做帧同步。
  2. 纠正采样和载波频偏
  3. 通过空时解码或者空频解码，在进行OFDM接收架构得到最终结果。
*** 关键技术
  - 空时或空频编解码 :: 只有通过空时解码才可以恢复从各个接收天线上得到的叠加信号。从而实现空间复用，增加可靠性或传输效率。
  - 帧同步和载波频偏估计 :: 突发模式传输必备，判断信号能量，和数据位置。
  - 采样时钟的同步和细载波频偏的纠正 :: 时钟偏差会引起ICI（载波间干扰），ISI（符号间干扰）
  - 信道估计 :: 信号估计由子信道构成，信道估计要细分到子信道。

     


